FROM rust:slim
RUN apt-get update && apt-get install -y pkg-config libssl-dev jq && rm -rf /var/lib/apt/lists/*
RUN cargo install --git https://github.com/Coko7/vegapull --locked
COPY scripts/docker-fetch.sh /fetch.sh
RUN chmod +x /fetch.sh

ENTRYPOINT ["/fetch.sh"]
