/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as CollectionIndexRouteImport } from './routes/collection/index'
import { Route as AuthCallbackRouteImport } from './routes/_auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionIndexRoute = CollectionIndexRouteImport.update({
  id: '/collection/',
  path: '/collection/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/_auth/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/collection/': typeof CollectionIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof AuthCallbackRoute
  '/collection': typeof CollectionIndexRoute
  '/series': typeof SeriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/callback': typeof AuthCallbackRoute
  '/collection/': typeof CollectionIndexRoute
  '/series/': typeof SeriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/callback' | '/collection/' | '/series/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/callback' | '/collection' | '/series'
  id: '__root__' | '/' | '/_auth/callback' | '/collection/' | '/series/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection/'
      preLoaderRoute: typeof CollectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/callback': {
      id: '/_auth/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CollectionIndexRoute: CollectionIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
